---@class SMPConfigDefaults
local SMPConfigDefaults = SMPLoader:CreateModule("SMPConfigDefaults")

function SMPConfigDefaults:Load()
    return {
        global = {
            dbVersion = 1,
            splits = {},
        },
        profile = {
            tooltip = {
                showSeparator = true,
                showDungeonListAlways = false,
                abbreviateDungeons = false,
            },

            search = {
                font = "Friz Quadrata TT",
                fontSize = 13,
                fontFlags = "",
            },

            overlay = {
                insertKeystoneAutomatically = true,
                showMillisecondsWhenDungeonCompleted = false,
                showPullBar = true,
                forcesFormat = ":percent:",
                customForcesFormat = ":percent:",
                currentPullFormat = "(+:percent:)",
                customCurrentPullFormat = "(+:percent:)",
                showTooltipCount = true,
                showForcesGlow = true,
                forcesGlowColor = "FF479AED",
                forcesGlowLineCount = 8,
                forcesGlowLength = 5,
                forcesGlowThickness = 2,
                forcesGlowFrequency = 0.2,
                showDeathsTooltip = true,
                deathLogStyle = "time",
                splitsEnabled = false,
                showSplitRecords = "always",
                splitRecordsColor = "FF479AED",
                fallbackSplitBehavior = "none",
                splitFasterTimeColor = "FF00FF00",
                splitSlowerTimeColor = "FFFF2020",
                frameScale = 1.0,
                framePadding = 8,
                alignTexts = "right",
                alignBarTexts = "right",
                alignBossClear = "start",
                verticalOffset = 4,
                objectivesOffset = 2,
                barPadding = 4,
                timerRunningColor = "FFFFFFFF",
                timerSuccessColor = "FFFFD100",
                timerExpiredColor = "FFFF2020",
                timerFont = "Friz Quadrata TT",
                timerFontSize = 20,
                timerFontFlags = "OUTLINE",
                deathsFont = "Friz Quadrata TT",
                deathsFontSize = 14,
                deathsFontFlags = "OUTLINE",
                deathsColor = "FFFFFFFF",
                keyFont = "Friz Quadrata TT",
                keyFontSize = 14,
                keyFontFlags = "OUTLINE",
                keyColor = "FFFFFFFF",
                keyDetailsFont = "Friz Quadrata TT",
                keyDetailsFontSize = 14,
                keyDetailsFontFlags = "OUTLINE",
                keyDetailsColor = "FFFFFFFF",
                barWidth = 280,
                barHeight = 14,
                backdropTexture = "Solid",
                backdropTextureColor = "FF000000",
                bar1Font = "Friz Quadrata TT",
                bar1FontSize = 12,
                bar1FontFlags = "OUTLINE",
                bar1Texture = "Solid",
                bar1TextureColor = "FFB3B3B3",
                bar2Font = "Friz Quadrata TT",
                bar2FontSize = 12,
                bar2FontFlags = "OUTLINE",
                bar2Texture = "Solid",
                bar2TextureColor = "FFB3B3B3",
                bar3Font = "Friz Quadrata TT",
                bar3FontSize = 12,
                bar3FontFlags = "OUTLINE",
                bar3Texture = "Solid",
                bar3TextureColor = "FFB3B3B3",
                forcesFont = "Friz Quadrata TT",
                forcesFontSize = 12,
                forcesFontFlags = "OUTLINE",
                forcesColor = "FFFFFFFF",
                completedForcesColor = "FF00FF00",
                forcesTexture = "Solid",
                forcesTextureColor = "FF479AED",
                forcesOverlayTexture = "Solid",
                forcesOverlayTextureColor = "FFFFD100",
                objectivesFont = "Friz Quadrata TT",
                objectivesFontFlags = "OUTLINE",
                objectivesFontSize = 14,
                objectivesColor = "FFFFFFFF",
                completedObjectivesColor = "FF00FF00",
            },
        },
    }
end
